# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Swimee1030' do
pod 'Alamofire','> 4.0.0'
end

target 'Swimee1030Tests' do

end

target 'Swimee1030UITests' do

end

